version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "4322:4322"
    environment:
      - NODE_ENV=development
      - PORT=4322
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_DISABLE_SANDBOX=true
      # API and Base URLs
      - API_BASE_URL=${API_BASE_URL}
      # Calendar
      - CALENDAR_API_KEY=${CALENDAR_API_KEY}
      - EVENT_CALENDAR_ID=${EVENT_CALENDAR_ID}
      # Email configuration
      - FROM_EMAIL=${FROM_EMAIL}
      - REPLY_TO_EMAIL=${REPLY_TO_EMAIL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      # MXRoute email configuration
      - MXROUTE_EMAIL_DOMAIN=${MXROUTE_EMAIL_DOMAIN}
      - MXROUTE_EMAIL_OUTBOUND_LIMIT=${MXROUTE_EMAIL_OUTBOUND_LIMIT}
      - MXROUTE_EMAIL_QUOTA=${MXROUTE_EMAIL_QUOTA}
      - MXROUTE_LOGIN_KEY=${MXROUTE_LOGIN_KEY}
      - MXROUTE_SERVER_LOGIN=${MXROUTE_SERVER_LOGIN}
      - MXROUTE_SERVER_URL=${MXROUTE_SERVER_URL}
      # Firebase environment variables
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - PUBLIC_FIREBASE_PROJECT_ID=${PUBLIC_FIREBASE_PROJECT_ID}
      - PUBLIC_FIREBASE_AUTH_DOMAIN=${PUBLIC_FIREBASE_AUTH_DOMAIN}
      - PUBLIC_FIREBASE_STORAGE_BUCKET=${PUBLIC_FIREBASE_STORAGE_BUCKET}
      - PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - PUBLIC_FIREBASE_APP_ID=${PUBLIC_FIREBASE_APP_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_AUTH_URL=${FIREBASE_AUTH_URL}
      - FIREBASE_TOKEN_URL=${FIREBASE_TOKEN_URL}
      - FIREBASE_AUTH_CERT_URL=${FIREBASE_AUTH_CERT_URL}
      - FIREBASE_CLIENT_CERT_URL=${FIREBASE_CLIENT_CERT_URL}
      - PUBLIC_FIREBASE_WEB_API_KEY=${PUBLIC_FIREBASE_WEB_API_KEY}
