/**
 * Convex API Integration
 *
 * This file provides the api and types exports for Convex integration.
 * The api object is auto-generated by Convex and references all
 * registered Convex functions.
 */

// Export the auto-generated api object
export { api, internal } from "../../../convex/_generated/api";

// Export types
export type { Id } from "../../../convex/_generated/dataModel";
